import Head from 'next/head'
import { Header } from '@/components/modules/header/Header'

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg" sizes="32x32" href="/img/logo.svg" />
      </Head>

      <Header />

      <main>
        <div className="overlay" />
      </main>
    </>
  )
}
